// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqw5-6hvNcamVwLxerMPpigAii8Kp3DDk',
    appId: '1:714446733377:web:fd676707ca617b3f71c6c0',
    messagingSenderId: '714446733377',
    projectId: 'project-94f02',
    authDomain: 'project-94f02.firebaseapp.com',
    databaseURL: 'https://project-94f02-default-rtdb.firebaseio.com',
    storageBucket: 'project-94f02.appspot.com',
    measurementId: 'G-YMPP9YSP76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBznV45UQr40OzhxDhFM6kylBxI1QifHmY',
    appId: '1:714446733377:android:0a8d61aac52d67f171c6c0',
    messagingSenderId: '714446733377',
    projectId: 'project-94f02',
    databaseURL: 'https://project-94f02-default-rtdb.firebaseio.com',
    storageBucket: 'project-94f02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Xjrc2FeGfv4f8c_McXjs-onyRgqnyJQ',
    appId: '1:714446733377:ios:a5aefb45ffd51cf271c6c0',
    messagingSenderId: '714446733377',
    projectId: 'project-94f02',
    databaseURL: 'https://project-94f02-default-rtdb.firebaseio.com',
    storageBucket: 'project-94f02.appspot.com',
    iosClientId: '714446733377-9qork0ojqt6pil87gudeggh69s4t6m9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.yogify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1Xjrc2FeGfv4f8c_McXjs-onyRgqnyJQ',
    appId: '1:714446733377:ios:a5aefb45ffd51cf271c6c0',
    messagingSenderId: '714446733377',
    projectId: 'project-94f02',
    databaseURL: 'https://project-94f02-default-rtdb.firebaseio.com',
    storageBucket: 'project-94f02.appspot.com',
    iosClientId: '714446733377-9qork0ojqt6pil87gudeggh69s4t6m9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.yogify',
  );
}
